### ISSUE TITLE
PHP 7: Mocking class with __toString() with return typehint causes Fatal error

### ISSUE THREAD

**Issue by simara-svatopluk** [padraic/mockery#533]
When I try to mock a class:

```php
class Printable {
	public function __toString() : string {
		return "";
	}
}

$mock = Mockery::mock(Printable::class);
```

Mockery fails:
`Fatal error: Declaration of Mockery_0_Printable::__toString() must be compatible with Printable::__toString(): string in /var/www/uni-core.l/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 25`

Of course, it's because of the return typehint. Temporary solution is removing ` : string`, and everything works well.

**Comment by robcaw** [comment]
Have you tried using the master branch? 

https://github.com/padraic/mockery/issues/523#issuecomment-162606632

**Comment by simara-svatopluk** [comment]
Good point. I've tried it right now, but it still produces the same Fatal error.

**Comment by robcaw** [comment]
Yep you're right. I was getting the same error for normal method return types, but using master fixed that. `__toString() : string` doesn't seem to have been fixed though.

**Comment by simara-svatopluk** [comment]
Thank You a lot :+1:

**Comment by ddcollins** [comment]
This error is still occurring for me in `0.9.10` with PHP `7.2.13`
